package com.userInterface;

import com.databases.DbInsertData;

import javax.swing.*;
import java.util.Arrays;

public class Register extends javax.swing.JFrame {

    /**
     * Creates new form com.userInterface.Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        registerPane = new javax.swing.JPanel();
        registerLbl = new javax.swing.JLabel();
        passwordTb = new javax.swing.JPasswordField();
        loginLinkLbl = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        usernameTb = new javax.swing.JTextField();
        usernameLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        firstnameTb = new javax.swing.JTextField();
        firstnameLbl = new javax.swing.JLabel();
        lastnameLbl = new javax.swing.JLabel();
        lastnameTB = new javax.swing.JTextField();
        reTypePassTb = new javax.swing.JPasswordField();
        retypePassLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));

        registerPane.setBackground(new java.awt.Color(201, 233, 246));

        registerLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        registerLbl.setText("com.userInterface.Register");

        javax.swing.GroupLayout registerPaneLayout = new javax.swing.GroupLayout(registerPane);
        registerPane.setLayout(registerPaneLayout);
        registerPaneLayout.setHorizontalGroup(
                registerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPaneLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(192, 192, 192))
        );
        registerPaneLayout.setVerticalGroup(
                registerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(registerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                .addContainerGap())
        );

        passwordTb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTbActionPerformed(evt);
            }
        });

        loginLinkLbl.setBackground(new java.awt.Color(100, 100, 200));
        loginLinkLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginLinkLbl.setForeground(new java.awt.Color(150, 150, 250));
        loginLinkLbl.setText("click here to login");
        loginLinkLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginLinkLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLinkLblMouseClicked(evt);
            }
        });

        registerBtn.setText("register");
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        usernameTb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameTb.setToolTipText("");
        usernameTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTbActionPerformed(evt);
            }
        });

        usernameLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameLbl.setText("Username:");

        passwordLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordLbl.setText("Password:");

        firstnameTb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstnameTb.setToolTipText("");
        firstnameTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTbActionPerformed(evt);
            }
        });

        firstnameLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstnameLbl.setText("First Name:");

        lastnameLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastnameLbl.setText("Last Name:");

        lastnameTB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastnameTB.setToolTipText("");
        lastnameTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTBActionPerformed(evt);
            }
        });

        reTypePassTb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reTypePassTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reTypePassTbActionPerformed(evt);
            }
        });

        retypePassLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        retypePassLbl.setText("Retype Pass:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(registerPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lastnameLbl)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lastnameTB, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(firstnameLbl)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(firstnameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(loginLinkLbl)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(registerBtn))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(passwordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(passwordTb, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(usernameLbl)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(usernameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(retypePassLbl)
                                                .addGap(18, 18, 18)
                                                .addComponent(reTypePassTb, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(registerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstnameLbl)
                                        .addComponent(firstnameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lastnameLbl)
                                        .addComponent(lastnameTB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameLbl)
                                        .addComponent(usernameTb, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordTb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(retypePassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(reTypePassTb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(loginLinkLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void passwordTbActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void loginLinkLblMouseClicked(java.awt.event.MouseEvent evt) {
        returnToLogin();
    }

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {
        String firstname = firstnameTb.getText();
        String lastname = lastnameTB.getText();
        String username = usernameTb.getText();
        char[] password = passwordTb.getPassword();

        if(!Arrays.equals(passwordTb.getPassword(), reTypePassTb.getPassword())){
            JOptionPane.showMessageDialog(this, "passwords do not match try again");
        }
        else{
            System.out.println("'"+username +"', '"+String.valueOf(password) +"', " +"NULL, '0', '', '"+firstname +"', '"+lastname+"'");
        }

        //input data into db
        String[] userData = new String[]{username, String.valueOf(password), firstname, lastname};
        DbInsertData.insertData("shareholderstbl", userData);

        //switch to login to make sure credentials are working
        returnToLogin();

    }

    private void returnToLogin(){
        Login lg = new Login();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }

    private void usernameTbActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void firstnameTbActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void lastnameTBActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void reTypePassTbActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel firstnameLbl;
    private javax.swing.JTextField firstnameTb;
    private javax.swing.JLabel lastnameLbl;
    private javax.swing.JTextField lastnameTB;
    private javax.swing.JLabel loginLinkLbl;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPasswordField passwordTb;
    private javax.swing.JPasswordField reTypePassTb;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel registerLbl;
    private javax.swing.JPanel registerPane;
    private javax.swing.JLabel retypePassLbl;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTb;
    // End of variables declaration
}
